version: '3.6'
services:       
    # # Hapi-FHIR -  SHR
    shr-hapi-fhir:
        container_name: shr-hapi-fhir
        image: hapiproject/hapi:v5.5.1
        depends_on:
            - shr-db
        ports:
            - "8090:8080"
        restart: always
        environment:
            - hapi.fhir.auto_create_placeholder_reference_targets=true
            - hapi.fhir.allow_placeholder_references=true
            - hapi.fhir.allow_external_references=true
            - hapi.fhir.client_id_strategy=ANY
            - hapi.fhir.mdm_enabled=false
            - spring.datasource.url=jdbc:postgresql://shr-db:5432/hapi
            - spring.datasource.username=admin
            - spring.datasource.password=admin
            - spring.datasource.driverClassName=org.postgresql.Driver
        volumes:
            - hapi-data:/data/hapi

    shr-db:
        image: postgres:14.4
        container_name: hapi-fhir-db
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: 'hapi'
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin'
        volumes:
            - hapi-fhir-db:/var/lib/postgresql/data

   #FHIR Pipeline
    pipeline-controller:
        image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
        container_name: pipeline-controller
        platform: linux/amd64
        volumes:
           - ./configs/fhirpipes/config:/app/config:ro
           - ./configs/fhirpipes/dwh:/dwh
        environment:
           - JAVA_OPTS=-Xms7g -Xmx7g
        ports:
           - '8095:8080'         
        
volumes:
  key_trust-store-volume:
  certs-vol:
  keys-vol:
  hapi-data:
  hapi-fhir-db: